services:
  db:
    image: postgres:17
    container_name: llmn_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - llmn_db_data:/var/lib/postgresql/data
volumes:
  llmn_db_data:
